{ stdenv
, imagemagick
, ffmpeg
, protobuf
, postgresql
, nodejs
, yarn
, libpqxx
, libxml2
, libxslt
, file
, git
, pkgconfig
, autoconf
, bison
, readline62
, zlib
, ncurses5
, libffi
, gdbm
, libidn
, icu
, pam
, ruby_2_6
, bundler
, bundlerEnv
, which
, fetchFromGitHub
, fetchurl
, fetchgit
, runCommand
, writeTextFile
, libtool
, utillinux
, python2
, nodejs-8_x
, buildEnv
}:


let
  version = "2.7.4";
  src = fetchFromGitHub {
    owner = "tootsuite";
    repo = "mastodon";
    rev = "v${version}";
    sha256 = "0x16c2m8d9nszr9hjw6j1i8gicvpgxzli5afaqd0z144y0ar62qa";
  };
  rubyEnv = bundlerEnv {
    name = "mastodon-env";
    inherit ruby_2_6;

    gemConfig = {
      "idn-ruby" = attrs: { buildInputs = [ libidn ]; };
      "charlock_holmes" = attrs: { buildInputs = [ which icu zlib ]; };
      nokogiri = attrs: { buildInputs = [ zlib ]; };
      pg = attrs: { buildInputs = [ postgresql ]; };
      cld3 = attrs: { buildInputs = [ protobuf pkgconfig ]; };
      ffi = attrs: { buildInputs = [ libffi pkgconfig ]; };
      # fetch git submodules, include a patch from upstream, where submodules
      # are linked by https:// instead of git://
      "http_parser.rb"= attrs: {
        source = attrs.source // { 
          fetchSubmodules = true;
          rev = "225354b3d94d8d76774bac5bb2ac0139dd75662c";
          sha256 = "00avimm11xnpsylgvr1rrcxr9ijsa3rygvqj8fzil0g73cypb7fx";
        }; 
      };
      rpam2 = attrs: { buildInputs = [ pam ]; };
    };

    # ?
    # buildInputs = [ bundler ];

    gemfile = "${src}/Gemfile";
    lockfile = "${src}/Gemfile.lock";
    # generated by bundix -l
    gemset = ./gemset.nix;

    groups = [
      "default"
      "development"
      "test"
    ];

    ignoreCollisions = true;
  };
  # node-packages*.nix generated via:
  #
  # % node2nix --nodejs-8 \
  #            --input package.json \
  #            --output node-packages-generated.nix \
  #            --composition node-packages.nix \
  #            --node-env ./../../development/node-packages/node-env.nix \
  #            --pkg-name nodejs-8_x
  nodeEnv = import ./node-packages-generated.nix {
    inherit fetchurl fetchgit;
    nodeEnv = import ../../development/node-packages/node-env.nix {
      inherit stdenv python2 utillinux runCommand writeTextFile;
      nodejs = nodejs-8_x;
      libtool = null;
    };
  };
in
stdenv.mkDerivation rec{
  name = "mastodon";
  inherit version src;

  env = buildEnv {
    name = "mastodon-env";
    paths = [
      imagemagick
      ffmpeg
      protobuf
      postgresql
      nodejs
      yarn
      libpqxx
      libxml2
      libxslt
      file
      git
      pkgconfig
      autoconf
      bison
      readline62
      zlib
      ncurses5
      libffi
      gdbm
      libidn
      icu
      # ruby_2_4
      # bundler

      rubyEnv
      nodeEnv.package
    ];
  };

  passthru = {
    inherit rubyEnv;
  };

  installPhase = ''
    mkdir -p $out
    # rm -r bin
    cp -R . $out/
  '';

}
