{ stdenv
, imagemagick
, ffmpeg
, protobuf
, postgresql
, nodejs
, yarn
, libpqxx
, libxml2
, libxslt
, file
, git
, pkgconfig
, autoconf
, bison
, readline62
, zlib
, ncurses5
, libffi
, gdbm
, libidn
, icu
, pam
, ruby_2_5
, bundler
, bundlerEnv
, which
, fetchFromGitHub
, fetchurl
, fetchgit
, runCommand
, writeTextFile
, libtool
, utillinux
, python2
, nodejs-8_x
, buildEnv
}:


let
  version = "2.6.2";
  src = fetchFromGitHub {
    owner = "tootsuite";
    repo = "mastodon";
    rev = "v${version}";
    sha256 = "0yj1lb091l9fp5myipjd9614g2yg0xvqhcphlbbgmh7lnywnswah";
  };
  rubyEnv = bundlerEnv {
    name = "mastodon-env";
    inherit ruby_2_5;

    gemConfig = {
      "idn-ruby" = attrs: { buildInputs = [ libidn ]; };
      "charlock_holmes" = attrs: { buildInputs = [ which icu zlib ]; };
      nokogiri = attrs: { buildInputs = [ zlib ]; };
      pg = attrs: { buildInputs = [ postgresql ]; };
      cld3 = attrs: { buildInputs = [ protobuf pkgconfig ]; };
      ffi = attrs: { buildInputs = [ libffi pkgconfig ]; };
      # fetch git submodules, include a patch from upstream, where submodules
      # are linked by https:// instead of git://
      "http_parser.rb"= attrs: { 
        source = attrs.source // { 
          fetchSubmodules = true;
          rev = "b89eababc1f103c5f1e54a72ed83fc2f89adb6a5";
          sha256 = "1mm30sd1k218fxlfziax2kyaqgib83j6lsxmn12qfb1hjybp5rml";
        }; 
      };
      rpam2 = attrs: { buildInputs = [ pam ]; };
    };

    buildInputs = [ bundler ];

    gemfile = "${src}/Gemfile";
    lockfile = "${src}/Gemfile.lock";
    # generated by bundix -l
    gemset = ./gemset.nix;

    groups = [
      "default"
      "development"
      "test"
    ];

    ignoreCollisions = true;
  };
  # node-packages*.nix generated via:
  #
  # % node2nix --input package.json \
  #            --output node-packages-generated.nix \
  #            --composition node-packages.nix \
  #            --node-env ./../../development/node-packages/node-env.nix \
  #            --pkg-name nodejs-8_x
  nodeEnv = import ./node-packages-generated.nix {
    inherit fetchurl fetchgit;
    nodeEnv = import ../../development/node-packages/node-env.nix {
      inherit stdenv python2 utillinux runCommand writeTextFile;
      nodejs = nodejs-8_x;
      libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
    };
  };
in
stdenv.mkDerivation rec{
  name = "mastodon";
  inherit version src;

  env = buildEnv {
    name = "mastodon-env";
    paths = [
      imagemagick
      ffmpeg
      protobuf
      postgresql
      nodejs
      yarn
      libpqxx
      libxml2
      libxslt
      file
      git
      pkgconfig
      autoconf
      bison
      readline62
      zlib
      ncurses5
      libffi
      gdbm
      libidn
      icu
      # ruby_2_4
      # bundler
      yarn

      rubyEnv
      nodeEnv.package
    ];
  };

  passthru = {
    inherit rubyEnv;
  };

  installPhase = ''
    mkdir -p $out
    # rm -r bin
    cp -R . $out/
  '';

}
